name: elastic beat release by goreleaser

on:
  push:
    tags:
      - '*'

env:
  GOPRIVATE: github.com/streamnative

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.1.1
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.BEAT_ACCESS_TOKEN }}
          GOPATH: /home/runner/work/pulsar-beat-output/pulsar-beat-output/go